add social (twitter,facebook,stackoverflow)
sabrinaluo/hexo-theme-replica pull request #28
Opened 2019-08-02 15:13 UTC by gjmvvv

2019-08-07 05:54 UTC, sabrinaluo requested changes

2019-08-07 05:54 UTC, sabrinaluo commented on layout/_partial/footer.ejs
> +      <li><a href="https://github.com/Kylin-Studio/">KyLin-Studio</a></li>
🤔

2019-08-13 14:48 UTC, sabrinaluo requested changes

2019-08-13 14:48 UTC, sabrinaluo commented on layout/_partial/footer.ejs
> -      <% if(github){ %>
这部分代码不建议删掉，否则footer的左边会很空，这部分也是模仿github本身的footer。删除该部分会影响现有用户的使用。

建议可以新加一个设置为`custom_footer_list`允许用户添加一个list，可以自定义名字和url

2019-08-13 15:47 UTC, CnTDou commented on layout/_partial/footer.ejs
> -      <% if(github){ %>
恩恩, 这块好像是误操作了  我这边改成我的按个团队组织了 所以把这个删除了, 这块pr错了  https://toud.cc  我下面改成自己的一个组织链接了

2019-08-13 15:48 UTC, CnTDou commented on layout/_partial/footer.ejs
> -      <% if(github){ %>
其次我这个语法不太会 期待你的添加 list 然后我 合并过来 改一下

2019-10-31 04:10 UTC, closed without merging